# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ConsumptionAnalyzeService/*
    - core-ci/*
pool:
  vmImage: 'windows-latest'

variables:
- name: subscription
  value: PAYG

steps:
- task: AzurePowerShell@5
  displayName: variables - set
  inputs:
    azureSubscription: ${{ variables.subscription }}
    scriptType: filePath
    scriptPath: $(System.DefaultWorkingDirectory)/core-ci/variables/setvariables.ps1
    azurePowerShellVersion: LatestVersion
    scriptArguments: -env dev
    pwsh: true

- task: AzurePowerShell@5
  displayName: storage - deploy
  inputs:
    azureSubscription: ${{ variables.subscription }}
    scriptType: filePath
    scriptPath: $(System.DefaultWorkingDirectory)/ConsumptionAnalyzeService/ci/infra/arm/deploy-arm.ps1
    azurePowerShellVersion: LatestVersion
    pwsh: true